### ISSUE TITLE
Adding metadata to a vApp or a specific VM is not supported

### ISSUE THREAD

**Issue by dn1s** [vmware/go-vcloud-director#160]
Right now the implementation of metadata is only working for the first VM in a vApp.
```
vapp.VApp.Children.VM[0].HREF
```

vm.go does not have a AddMetadata function.

**Comment by vbauzysvmware** [comment]
I wonder if this fixes also #158. 
@Didainius

**Comment by dn1s** [comment]
Oh it does. This pull request is also related to https://github.com/terraform-providers/terraform-provider-vcd/issues/158

**Comment by Didainius** [comment]
@dn1s thanks for this and sorry it's been stale for some time. We're catching up on the repo after Go modules. Could you resolve conflicts with the latest stuff in master.

I've looked at this and ran tests (directly from your branch rather than merging it with current master).

The only concern I'd have is with backwards compatibility. Suppose someone had metadata on the first VM (which I know is odd behaviour) with `func (vapp *VApp) AddMetadata/DeleteMetadata`, but after we release this the behavior changes.

What are your own thoughts on this?

**Comment by dn1s** [comment]
Fixed issue with merge of #161
